version: "3.9"
services:

  api:
   build: .
   ports:
     - 3000:3000
   container_name: mern-api
   restart: always
   depends_on:
    wait-for-db:
        condition: service_completed_successfully


  wait-for-db:
    image: atkrad/wait4x
    depends_on:
      - db
    command: tcp db:3306 -t 30s -i 250ms
  

  db:
    container_name: mysql-db
    image: mysql
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: 'rtfgcv'
       MYSQL_DATABASE: 'testiong'
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    depends_on:
    - cache
  phpmyadmin:
    image: phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80


  cache:
    image: redis
    restart: always
    ports:
      - 6379:6379
    container_name: redis-cache
    command: [ "redis-server" ]
    volumes: 
      - redis-data:/data


volumes:
  mysql-data:
    driver: local
  redis-data:
    driver: local